### ISSUE TITLE
Opening supported links by default

### ISSUE THREAD

**Issue by siavash79** [bennyboer/bbb_app#132]
Hi

I suggest that the app adds an option in the settings to add supported domain names, for which it can set to open by default.

This way, by clicking on the meeting link anywhere across the phone, it can directly enter the meeting through the app. (Also may need a default participant name to be set in settings as well)

**Comment by bennyboer** [comment]
Hi there, sorry for the delay!
Since host names for BBB servers may be very different, we decided to go another way and offer a "redirect" service.
You can specify your meeting URL (both Greenlight URLs and direct join URLs using the `target` query parameter): e. g. https://bennyboer.github.io/bbb_app/?target=https://MY-BBB-HOSTNAME.com/b/abc-d-efg

The redirect web app will prompt the user to either open the meeting in the installed app or use the official web app.

Does this already solve your problem?

**Comment by siavash79** [comment]
That's a really good workaround, and yes it satisfies the need nicely.
