### ISSUE TITLE
[not an issue] Just a question

### ISSUE THREAD

**Issue by abyasoft** [bennyboer/bbb_app#75]
Hello;

First, you're doing a good job.

I have an installation of bbb that works well on a vps.
I have created a REST API using codeigniter to interact with bbb.
In the REST API, users are registered and access meetings using their credentials.
The question is how can I modify the work-flow of your app to use it in my context.

Thank you in advance.

**Comment by bennyboer** [comment]
Hi there! So you are having users joining using their credentials (username and password based?) instead of using BBB meetings that are protected by an access code? Do they still need to provide the proper URL of the meeting?

Currently we do only support joining meetings by providing the URL and an access code (if needed). Maybe you'd want to take a look into the `StartView` (https://github.com/bennyboer/bbb_app/blob/main/lib/src/view/start/start_view.dart) on how the join process is currently done.

**Comment by abyasoft** [comment]
Thank you for the quick reply

**Comment by bennyboer** [comment]
I am going to close this issue, if you have further questions feel free to reopen it 😄
